name: whatsapp_unilink
description: Dart package helping your app interact with WhatsApp via HTTP links (universal links). Works with Flutter.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  # version: ^1.0.3
